-- Update Logos Script
UPDATE racers SET logo_url = '/soulgrid/shock_C45zM-w58.webp' WHERE name = 'Shocker';
UPDATE racers SET logo_url = '/soulgrid/arc_vYu2btxAd.webp' WHERE name = 'Ark Nemesis';
UPDATE racers SET logo_url = '/soulgrid/broken bikers.webp' WHERE name = 'Broken Biker';
UPDATE racers SET logo_url = '/soulgrid/vision__1__EnTESPJ-M.webp' WHERE name = 'Vision';
UPDATE racers SET logo_url = '/soulgrid/MomentZMotorsport__1__Mdg88VcPe.webp' WHERE name = 'Momentz Motorsports';
UPDATE racers SET logo_url = '/soulgrid/amore__1__Iwkpdvc8J.webp' WHERE name = 'Amore McQueens';
UPDATE racers SET logo_url = '/soulgrid/locked_racing_background_removed__1__jnCAeqyfna.webp' WHERE name = 'Locked & Racing';
UPDATE racers SET logo_url = '/soulgrid/injector.webp' WHERE name = 'Injector';
UPDATE racers SET logo_url = '/soulgrid/arnox.webp' WHERE name = 'ARN0UX';
UPDATE racers SET logo_url = '/soulgrid/JoyBoy__1__ebVAJAflx.webp' WHERE name = 'JOYBOY';
UPDATE racers SET logo_url = '/soulgrid/hunt.webp' WHERE name = 'HUNT';
UPDATE racers SET logo_url = '/soulgrid/suidhaga.webp' WHERE name = 'SUIDHAGA';
UPDATE racers SET logo_url = '/soulgrid/rawsoe,.webp' WHERE name = 'RAWKILL';
UPDATE racers SET logo_url = '/soulgrid/faint.webp' WHERE name = 'Faint';
UPDATE racers SET logo_url = '/soulgrid/fuka.webp' WHERE name = 'FUKKA';
UPDATE racers SET logo_url = '/soulgrid/chunkey.webp' WHERE name = 'CHUNKEY';
UPDATE racers SET logo_url = '/soulgrid/burnout.webp' WHERE name = 'BURNOUT';
UPDATE racers SET logo_url = '/soulgrid/naxx.webp' WHERE name = 'NAXX';
UPDATE racers SET logo_url = '/soulgrid/mortom.webp' WHERE name = 'MORTOM';
UPDATE racers SET logo_url = '/soulgrid/brutal.webp' WHERE name = 'BRUTAL';
UPDATE racers SET logo_url = '/soulgrid/chili.webp' WHERE name = 'CHILLIPOTATO';
UPDATE racers SET logo_url = '/soulgrid/subus.webp' WHERE name = 'SUBUWU';
UPDATE racers SET logo_url = '/soulgrid/otaku.webp' WHERE name = 'OTAKU';
UPDATE racers SET logo_url = '/soulgrid/sakura.webp' WHERE name = 'SAKURA';
UPDATE racers SET logo_url = '/soulgrid/exo_8hXCmPI_b.webp' WHERE name = 'Exo Shifters';
UPDATE racers SET logo_url = '/soulgrid/unicorn_QqJWd7IsE.webp' WHERE name = 'Speed Unicorn';
UPDATE racers SET logo_url = '/soulgrid/ez_final_V8H9Tqs8e.webp' WHERE name = 'Empire Zoomies';
UPDATE racers SET logo_url = '/soulgrid/bb__1__l-jE5_Xgz.webp' WHERE name = 'Bennys Burnout';
UPDATE racers SET logo_url = '/soulgrid/pegasus_m4zT083xZ.webp' WHERE name = 'Blackwings of Pegasus';
UPDATE racers SET logo_url = '/soulgrid/Marlboro.webp' WHERE name = 'MARLBORO';
UPDATE racers SET logo_url = '/soulgrid/m4.webp' WHERE name = 'M4';
UPDATE racers SET logo_url = '/soulgrid/yeat.webp' WHERE name = 'YE4T';
UPDATE racers SET logo_url = '/soulgrid/phase.webp' WHERE name = 'PHAZE';
UPDATE racers SET logo_url = '/soulgrid/gem.webp' WHERE name = 'DIAMOUND';
UPDATE racers SET logo_url = '/soulgrid/jinx.webp' WHERE name = 'JINX';
UPDATE racers SET logo_url = '/soulgrid/Scratch.webp' WHERE name = 'SCRATCH';
UPDATE racers SET logo_url = '/soulgrid/spellbound.webp' WHERE name = 'SpellBound';
UPDATE racers SET logo_url = '/soulgrid/arsh.webp' WHERE name = 'ARSH';
UPDATE racers SET logo_url = '/soulgrid/winter.webp' WHERE name = 'WINTER';
UPDATE racers SET logo_url = '/soulgrid/panic.webp' WHERE name = 'PAENIC';
UPDATE racers SET logo_url = '/soulgrid/hycade.webp' WHERE name = 'HYCADE';
UPDATE racers SET logo_url = '/soulgrid/soba.webp' WHERE name = '$OBA';
UPDATE racers SET logo_url = '/soulgrid/nomad.webp' WHERE name = 'NoMad';
UPDATE racers SET logo_url = '/soulgrid/asd.webp' WHERE name = 'ASD';
UPDATE racers SET logo_url = '/soulgrid/kidbo.webp' WHERE name = 'Kidboo';
UPDATE racers SET logo_url = '/soulgrid/burgir.webp' WHERE name = 'BURGIR';
UPDATE racers SET logo_url = '/soulgrid/phantom.webp' WHERE name = 'PH4NTOM';
UPDATE racers SET logo_url = '/soulgrid/wreker.webp' WHERE name = 'WRECKER';
UPDATE racers SET logo_url = '/soulgrid/gem.webp' WHERE name = 'GEM';
UPDATE racers SET logo_url = '/soulgrid/devil.webp' WHERE name = 'DEVIL';
UPDATE racers SET logo_url = '/soulgrid/crash.webp' WHERE name = 'Crash';
UPDATE racers SET logo_url = '/soulgrid/rizu.webp' WHERE name = 'Riju';
UPDATE racers SET logo_url = '/soulgrid/wububs.webp' WHERE name = 'WUBBUBS';
UPDATE racers SET logo_url = '/soulgrid/thunder.webp' WHERE name = 'THUNDER';
UPDATE racers SET logo_url = '/soulgrid/wicked.webp' WHERE name = 'Wicked';
UPDATE racers SET logo_url = '/soulgrid/ges.webp' WHERE name = 'GES';
UPDATE racers SET logo_url = '/soulgrid/rusher.webp' WHERE name = 'Punisher';
UPDATE racers SET logo_url = '/soulgrid/flack.webp' WHERE name = 'FL4CK';
UPDATE racers SET logo_url = '/soulgrid/anya.webp' WHERE name = 'ANYA';
UPDATE racers SET logo_url = '/soulgrid/strawberry.webp' WHERE name = 'Strawberry';
UPDATE racers SET logo_url = '/soulgrid/xero.webp' WHERE name = 'XERO';
UPDATE racers SET logo_url = '/soulgrid/hero.webp' WHERE name = 'HERO';
UPDATE racers SET logo_url = '/soulgrid/momo.webp' WHERE name = 'MOMO';
UPDATE racers SET logo_url = '/soulgrid/veno,m.webp' WHERE name = 'V3NOM';
UPDATE racers SET logo_url = '/soulgrid/zzz.webp' WHERE name = 'ZZZ';
UPDATE racers SET logo_url = '/soulgrid/shiro.webp' WHERE name = 'sh1ro';
UPDATE racers SET logo_url = '/soulgrid/arde.webp' WHERE name = 'ARDEE';
UPDATE racers SET logo_url = '/soulgrid/high.webp' WHERE name = 'GHOST';
UPDATE racers SET logo_url = '/soulgrid/bold.webp' WHERE name = 'BOLD';
UPDATE racers SET logo_url = '/soulgrid/bunnyt.webp' WHERE name = 'BUNNY';
UPDATE racers SET logo_url = '/soulgrid/guffball.webp' WHERE name = 'GUFFBALL';
UPDATE racers SET logo_url = '/soulgrid/zalim.webp' WHERE name = 'ZALIM-007';
UPDATE racers SET logo_url = '/soulgrid/snow.webp' WHERE name = 'Snow';
UPDATE racers SET logo_url = '/soulgrid/majest.webp' WHERE name = 'MAJESTY';
UPDATE racers SET logo_url = '/soulgrid/mirchi.webp' WHERE name = 'LAALM1RCH1';
UPDATE racers SET logo_url = '/soulgrid/mew.webp' WHERE name = 'MEW';
UPDATE racers SET logo_url = '/soulgrid/jugni.webp' WHERE name = 'JUGNI';
UPDATE racers SET logo_url = '/soulgrid/chotu.webp' WHERE name = 'Chotu18';
UPDATE racers SET logo_url = '/soulgrid/tanjiro.webp' WHERE name = 'TANJ1R0';
UPDATE racers SET logo_url = '/soulgrid/kek.webp' WHERE name = 'KEK';
UPDATE racers SET logo_url = '/soulgrid/dhapong.webp' WHERE name = 'DHAPONG';
UPDATE racers SET logo_url = '/soulgrid/moneyking.webp' WHERE name = 'MONKEYKING';
UPDATE racers SET logo_url = '/soulgrid/zephyr.webp' WHERE name = 'ZephyR';
UPDATE racers SET logo_url = '/soulgrid/trex.webp' WHERE name = 'T-R3X';
UPDATE racers SET logo_url = '/soulgrid/wasabi.webp' WHERE name = 'WASABI';
UPDATE racers SET logo_url = '/soulgrid/broly.webp' WHERE name = 'BROLY';
UPDATE racers SET logo_url = '/soulgrid/bamcha.webp' WHERE name = 'BAMCHA';
UPDATE racers SET logo_url = '/soulgrid/baji.webp' WHERE name = 'BAJ1';
UPDATE racers SET logo_url = '/soulgrid/ryuke.webp' WHERE name = 'Ryuke';
UPDATE racers SET logo_url = '/soulgrid/phoenix.webp' WHERE name = 'PHOENIX';
UPDATE racers SET logo_url = '/soulgrid/zeby.webp' WHERE name = 'ZEBY';
UPDATE racers SET logo_url = '/soulgrid/wicked.webp' WHERE name = 'W1CK3D';
UPDATE racers SET logo_url = '/soulgrid/twisted.webp' WHERE name = 'TW1ST3D';
UPDATE racers SET logo_url = '/soulgrid/enzo.webp' WHERE name = 'ENZO';
UPDATE racers SET logo_url = '/soulgrid/qube.webp' WHERE name = 'QUBE';
UPDATE racers SET logo_url = '/soulgrid/athena.webp' WHERE name = 'ATHENA';
UPDATE racers SET logo_url = '/soulgrid/rain.webp' WHERE name = 'Rain';
UPDATE racers SET logo_url = '/soulgrid/br_CrW0jdf-t.webp' WHERE name = 'Bee Rush';
UPDATE racers SET logo_url = '/soulgrid/spide.webp' WHERE name = 'GHOST';
UPDATE racers SET logo_url = '/soulgrid/zerko.webp' WHERE name = 'ZERKO';
UPDATE racers SET logo_url = '/soulgrid/poison.webp' WHERE name = 'POISON';
UPDATE racers SET logo_url = '/soulgrid/EL-DRAGO.webp' WHERE name = 'eL-DRAGO';
